auto: true # tip: when I had bad syntax in a post, setting this to false actually made the error appear
markdown: rdiscount
pygments: true
paginate: 5

title: yelyah
url: http://yelyah.com
tumblr_embed_color: BDBDBD